# Copyright (c) 2018 Tianyi Zhang
# Copyright (c) 2018 Parsa Amini
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

version: 2
anchors:
    - &docker_config
        docker:
            - image: stellargroup/hpx:dev
              entrypoint: /bin/bash

################################################################################
jobs:
    build_test:
        <<: *docker_config
        working_directory: /hpxMP
        steps:
            - checkout:
                path:
                    /hpxMP
            # CMake
            - run:
                name: Run CMake
                command: cmake -H. -Bbuild -DHPX_DIR=/usr/local/lib/cmake/HPX -DCMAKE_BUILD_TYPE=Debug -DHPXMP_WITH_OMPT=On
            # Build all targets
            - run:
                name: Build all targets
                command: cmake --build build -- -j2
            # Run all tests
            - run:
                name: Run all the tests
                command: cmake --build build -- -j2 test

################################################################################
workflows:
    version: 2
    build_and_test_phylanx:
        jobs:
            - build_test

